name: 'CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: '16.13.0'
      - name: 'Install dependencies'
        run: npm install

      - name: 'Fire up test server'
        run: npm run-script test-server

      - name: Wait for server to start
        run: sleep 5
        
      - name: 'Run tests'
        run: npm test


 